package InterfazGrafica;

import BaseDatos.MetodosBD;
import Clases.Profesor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Borja
 */

public class Interfaz extends javax.swing.JFrame {
    /**
     * Creates new form Interfaz
     */
    //   private final ProfesorDAOImp profesorDAO;
    private Profesor profesor;
    public Interfaz() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        botoncerrar = new javax.swing.JPanel();
        iconocerrar = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        introducecorreo = new javax.swing.JTextField();
        contraseña = new javax.swing.JLabel();
        introducecontrasena = new javax.swing.JPasswordField();
        botonlogin = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Login"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setOpaque(false);
        header.setPreferredSize(new java.awt.Dimension(900, 50));
        header.setLayout(new java.awt.BorderLayout());

        botoncerrar.setOpaque(false);
        botoncerrar.setPreferredSize(new java.awt.Dimension(50, 50));
        botoncerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconocerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconocerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconocerrar.png"))); // NOI18N
        iconocerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconocerrarMouseClicked(evt);
            }
        });
        botoncerrar.add(iconocerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        header.add(botoncerrar, java.awt.BorderLayout.LINE_END);

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        login.setOpaque(false);
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logointerfaz.png"))); // NOI18N
        login.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, 210));

        correo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        correo.setForeground(new java.awt.Color(255, 255, 255));
        correo.setText("Correo");
        login.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, 40));

        introducecorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introducecorreoActionPerformed(evt);
            }
        });
        login.add(introducecorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 350, 40));

        contraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        contraseña.setForeground(new java.awt.Color(255, 255, 255));
        contraseña.setText("Contraseña");
        login.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 170, 40));

        introducecontrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introducecontrasenaActionPerformed(evt);
            }
        });
        introducecontrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                introducecontrasenaKeyPressed(evt);
            }
        });
        login.add(introducecontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 350, 40));

        botonlogin.setBackground(new java.awt.Color(60, 63, 65));
        botonlogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonlogin.setForeground(new java.awt.Color(255, 255, 255));
        botonlogin.setText("Login");
        getRootPane().setDefaultButton(botonlogin);
        botonlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonloginMouseClicked(evt);
            }
        });
        botonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonloginActionPerformed(evt);
            }
        });
        login.add(botonlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 140, 60));

        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 400, 600));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Montaña.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(900, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void introducecorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introducecorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introducecorreoActionPerformed

    private void iconocerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconocerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_iconocerrarMouseClicked

    private void botonloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonloginMouseClicked
        MetodosBD bd= new MetodosBD();
        botonlogin.addActionListener((java.awt.event.ActionEvent e) -> {
            String correo = introducecorreo.getText();
            String contraseña = introducecontrasena.getText();

             profesor = bd.verificarCredencialesProfesor(correo, contraseña);
            if (profesor != null) {
                // Las credenciales son correctas, puedes permitir el acceso
                JOptionPane.showMessageDialog(null, "¡Bienvenido!");
                // Aquí puedes abrir la siguiente ventana o realizar alguna acción adicional
                aplicacion aplicacion = new aplicacion();
                aplicacion.setProfesor(profesor);
                aplicacion.setVisible(true);
                this.dispose();
            } else {
                // Las credenciales son incorrectas
                JOptionPane.showMessageDialog(null, "Correo o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });


    }//GEN-LAST:event_botonloginMouseClicked

    private void botonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonloginActionPerformed

    }//GEN-LAST:event_botonloginActionPerformed

    private void introducecontrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introducecontrasenaActionPerformed
    
    }//GEN-LAST:event_introducecontrasenaActionPerformed

    private void introducecontrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_introducecontrasenaKeyPressed
       
    }//GEN-LAST:event_introducecontrasenaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel botoncerrar;
    private javax.swing.JButton botonlogin;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel correo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel iconocerrar;
    private javax.swing.JPasswordField introducecontrasena;
    private javax.swing.JTextField introducecorreo;
    private javax.swing.JPanel login;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
